"""add tool_registry table

Revision ID: 15e2011f540e
Revises: eba2cf0e7d47
Create Date: 2026-10-02 22:26:58.077313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15e2011f540e'
down_revision: Union[str, Sequence[str], None] = 'eba2cf0e7d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_registry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server_id', sa.String(length=64), nullable=False),
    sa.Column('server_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('tool_version', sa.String(length=32), nullable=False),
    sa.Column('description_hash', sa.String(length=128), nullable=False),
    sa.Column('input_schema_hash', sa.String(length=128), nullable=False),
    sa.Column('output_schema_hash', sa.String(length=128), nullable=False),
    sa.Column('capability_hash', sa.String(length=128), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('output_labels', sa.String(length=255), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_registry_server_id'), 'tool_registry', ['server_id'], unique=False)
    op.create_index(op.f('ix_tool_registry_tool_name'), 'tool_registry', ['tool_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_registry_tool_name'), table_name='tool_registry')
    op.drop_index(op.f('ix_tool_registry_server_id'), table_name='tool_registry')
    op.drop_table('tool_registry')
    # ### end Alembic commands ###
