"""add policy_rules table

Revision ID: 191789771ce5
Revises: 15e2011f540e
Create Date: 2026-10-02 22:29:29.696392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '191789771ce5'
down_revision: Union[str, Sequence[str], None] = '15e2011f540e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('policy_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.String(length=32), nullable=False),
    sa.Column('subject_role', sa.String(length=64), nullable=True),
    sa.Column('tool_name', sa.String(length=128), nullable=True),
    sa.Column('source_label', sa.String(length=32), nullable=True),
    sa.Column('sink_type', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_rules_policy_id'), 'policy_rules', ['policy_id'], unique=True)
    op.create_index(op.f('ix_policy_rules_rule_type'), 'policy_rules', ['rule_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_rules_rule_type'), table_name='policy_rules')
    op.drop_index(op.f('ix_policy_rules_policy_id'), table_name='policy_rules')
    op.drop_table('policy_rules')
    # ### end Alembic commands ###
