"""add audit_events table

Revision ID: b37f620a4564
Revises: 191789771ce5
Create Date: 2026-10-02 22:31:11.465570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b37f620a4564'
down_revision: Union[str, Sequence[str], None] = '191789771ce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('subject', sa.String(length=64), nullable=True),
    sa.Column('agent', sa.String(length=64), nullable=True),
    sa.Column('server_id', sa.String(length=64), nullable=True),
    sa.Column('tool_name', sa.String(length=128), nullable=True),
    sa.Column('gate_results', sa.Text(), nullable=True),
    sa.Column('policy_action', sa.String(length=32), nullable=False),
    sa.Column('policy_reason', sa.String(length=128), nullable=True),
    sa.Column('input_hash', sa.String(length=128), nullable=True),
    sa.Column('tool_schema_hash', sa.String(length=128), nullable=True),
    sa.Column('result_hash', sa.String(length=128), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('prev_hash', sa.String(length=128), nullable=True),
    sa.Column('event_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_event_id'), 'audit_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_audit_events_policy_action'), 'audit_events', ['policy_action'], unique=False)
    op.create_index(op.f('ix_audit_events_session_id'), 'audit_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_events_timestamp'), 'audit_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_events_tool_name'), 'audit_events', ['tool_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_events_tool_name'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_timestamp'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_session_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_policy_action'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
