"""add approvals table

Revision ID: ed6d95478726
Revises: b37f620a4564
Create Date: 2026-10-02 22:33:31.458627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed6d95478726'
down_revision: Union[str, Sequence[str], None] = 'b37f620a4564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('approval_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('action_payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('approver_id', sa.String(length=64), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('second_approver_id', sa.String(length=64), nullable=True),
    sa.Column('second_approved_at', sa.DateTime(), nullable=True),
    sa.Column('approval_token_jti', sa.String(length=64), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('verification_code_sent', sa.Boolean(), nullable=False),
    sa.Column('verification_code_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('approval_token_jti')
    )
    op.create_index(op.f('ix_approvals_action'), 'approvals', ['action'], unique=False)
    op.create_index(op.f('ix_approvals_approval_id'), 'approvals', ['approval_id'], unique=True)
    op.create_index(op.f('ix_approvals_requested_by'), 'approvals', ['requested_by'], unique=False)
    op.create_index(op.f('ix_approvals_session_id'), 'approvals', ['session_id'], unique=False)
    op.create_index(op.f('ix_approvals_status'), 'approvals', ['status'], unique=False)
    op.create_index(op.f('ix_approvals_tenant_id'), 'approvals', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approvals_tenant_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_status'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_session_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_requested_by'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_approval_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_action'), table_name='approvals')
    op.drop_table('approvals')
    # ### end Alembic commands ###
